application: fireworkscomputer 
version: 4
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /guide
  static_dir: static/guide
  mime_type: text/html

- url: /pages
  static_dir: static/pages

- url: /mozilla-downloads
  static_dir: static/mozilla-downloads
  secure: always 
 
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
 
- url: /sitemap\.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml
 
- url: /googlef734612d306d87e6\.html
  static_files: static/googlef734612d306d87e6.html
  upload: static/googlef734612d306d87e6.html

- url: /.*
  script: request.py
