application: fireworkscomputer 
version: 3
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /pages
  static_dir: static/pages

- url: /mozilla-downloads
  static_dir: static/mozilla-downloads
  secure: always 

- url: /.*
  script: request.py

- url: /.*
  script: not_found.py
